// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CRIS.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// EndpointDataDefinition
    /// </summary>
    public partial class EndpointDataDefinition
    {
        /// <summary>
        /// Initializes a new instance of the EndpointDataDefinition class.
        /// </summary>
        public EndpointDataDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EndpointDataDefinition class.
        /// </summary>
        /// <param name="startDate">The start date of the demplyment data
        /// export</param>
        /// <param name="endDate">The end date of the demplyment data
        /// export</param>
        public EndpointDataDefinition(System.DateTime startDate, System.DateTime endDate)
        {
            StartDate = startDate;
            EndDate = endDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the start date of the demplyment data export
        /// </summary>
        [JsonProperty(PropertyName = "startDate")]
        public System.DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or sets the end date of the demplyment data export
        /// </summary>
        [JsonProperty(PropertyName = "endDate")]
        public System.DateTime EndDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
