// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CRIS.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// IReadOnlyDictionary`2
    /// </summary>
    public partial class GetSupportedLocalesForModelsOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetSupportedLocalesForModelsOKResponse class.
        /// </summary>
        public GetSupportedLocalesForModelsOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// GetSupportedLocalesForModelsOKResponse class.
        /// </summary>
        public GetSupportedLocalesForModelsOKResponse(IList<string> acoustic = default(IList<string>), IList<string> language = default(IList<string>), IList<string> acousticAndLanguage = default(IList<string>), IList<string> customVoice = default(IList<string>), IList<string> languageGeneration = default(IList<string>))
        {
            Acoustic = acoustic;
            Language = language;
            AcousticAndLanguage = acousticAndLanguage;
            CustomVoice = customVoice;
            LanguageGeneration = languageGeneration;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Acoustic")]
        public IList<string> Acoustic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Language")]
        public IList<string> Language { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AcousticAndLanguage")]
        public IList<string> AcousticAndLanguage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomVoice")]
        public IList<string> CustomVoice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LanguageGeneration")]
        public IList<string> LanguageGeneration { get; set; }

    }
}
