// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CRIS.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// HealthStatusResponse
    /// </summary>
    public partial class HealthStatusResponse
    {
        /// <summary>
        /// Initializes a new instance of the HealthStatusResponse class.
        /// </summary>
        public HealthStatusResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HealthStatusResponse class.
        /// </summary>
        /// <param name="status">Possible values include: 'Healthy', 'Sick',
        /// 'Error'</param>
        public HealthStatusResponse(string status = default(string), string message = default(string), IList<Component> components = default(IList<Component>))
        {
            Status = status;
            Message = message;
            Components = components;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Healthy', 'Sick', 'Error'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "components")]
        public IList<Component> Components { get; set; }

    }
}
