// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CRIS.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Model
    /// </summary>
    public partial class Model : Entity
    {
        /// <summary>
        /// Initializes a new instance of the Model class.
        /// </summary>
        public Model()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Model class.
        /// </summary>
        /// <param name="id">The identifier of this entity</param>
        /// <param name="modelKind">The kind of this model (e.g. acoustic,
        /// language ...). Possible values include: 'Acoustic', 'Language',
        /// 'AcousticAndLanguage', 'CustomVoice', 'LanguageGeneration'</param>
        /// <param name="name">The name of the object</param>
        /// <param name="locale">The locale of the contained data</param>
        /// <param name="createdDateTime">The time-stamp when the object was
        /// created</param>
        /// <param name="lastActionDateTime">The time-stamp when the current
        /// status was entered</param>
        /// <param name="status">The status of the object. Possible values
        /// include: 'NotStarted', 'Running', 'Succeeded', 'Failed'</param>
        /// <param name="baseModel">The base model used for adaptation</param>
        /// <param name="datasets">Datasets used for adaptation</param>
        /// <param name="description">The description of the object</param>
        /// <param name="properties">The custom properties of this
        /// entity</param>
        public Model(System.Guid id, string modelKind, string name, string locale, System.DateTime createdDateTime, System.DateTime lastActionDateTime, string status, Model baseModel = default(Model), IList<Dataset> datasets = default(IList<Dataset>), string description = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            Id = id;
            BaseModel = baseModel;
            Datasets = datasets;
            ModelKind = modelKind;
            Name = name;
            Description = description;
            Properties = properties;
            Locale = locale;
            CreatedDateTime = createdDateTime;
            LastActionDateTime = lastActionDateTime;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the base model used for adaptation
        /// </summary>
        [JsonProperty(PropertyName = "baseModel")]
        public Model BaseModel { get; set; }

        /// <summary>
        /// Gets or sets datasets used for adaptation
        /// </summary>
        [JsonProperty(PropertyName = "datasets")]
        public IList<Dataset> Datasets { get; set; }

        /// <summary>
        /// Gets or sets the kind of this model (e.g. acoustic, language ...).
        /// Possible values include: 'Acoustic', 'Language',
        /// 'AcousticAndLanguage', 'CustomVoice', 'LanguageGeneration'
        /// </summary>
        [JsonProperty(PropertyName = "modelKind")]
        public string ModelKind { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ModelKind == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ModelKind");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Locale == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Locale");
            }
            if (Status == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Status");
            }
            if (BaseModel != null)
            {
                BaseModel.Validate();
            }
            if (Datasets != null)
            {
                foreach (var element in Datasets)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
