// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CRIS.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// TestDefinition
    /// </summary>
    public partial class TestDefinition
    {
        /// <summary>
        /// Initializes a new instance of the TestDefinition class.
        /// </summary>
        public TestDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TestDefinition class.
        /// </summary>
        /// <param name="dataset">Information about the dataset used in the
        /// test</param>
        /// <param name="modelsProperty">Information about the models used for
        /// this accuracy test</param>
        /// <param name="name">The name of the object</param>
        /// <param name="description">The description of the object</param>
        /// <param name="properties">The custom properties of this
        /// entity</param>
        public TestDefinition(DatasetIdentity dataset, IList<ModelIdentity> modelsProperty, string name, string description = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            Dataset = dataset;
            ModelsProperty = modelsProperty;
            Name = name;
            Description = description;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets information about the dataset used in the test
        /// </summary>
        [JsonProperty(PropertyName = "dataset")]
        public DatasetIdentity Dataset { get; set; }

        /// <summary>
        /// Gets or sets information about the models used for this accuracy
        /// test
        /// </summary>
        [JsonProperty(PropertyName = "models")]
        public IList<ModelIdentity> ModelsProperty { get; set; }

        /// <summary>
        /// Gets or sets the name of the object
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the custom properties of this entity
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Dataset == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Dataset");
            }
            if (ModelsProperty == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ModelsProperty");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Dataset != null)
            {
                Dataset.Validate();
            }
            if (ModelsProperty != null)
            {
                foreach (var element in ModelsProperty)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
